### ISSUE TITLE
How to quickly select the area to plot?

### ISSUE THREAD

**Issue by zhanglab2008** [kharchenkolab/BaysorAnalysis#1]
Hi team!
Fantastic work! I was able to run baysor on my data and get the expected output. I just have one simple question.
When you select the area to plot, how you decide the coordinates to select?
```bash
subset_coords = [
    ((-2872, -2822), (-2371, -2300)), 
    ((-2820, -2770), (-2300, -2325)),
    ((-2715, -2665), (-2350, -2275)),
    ((-2400, -2300), (-2750, -2600)),
    ((-2410, -2310), (-3225, -3075))
];

plt = B.plot_dataset_colors(@where(df_spatial, :x .>= -3180, :x .<= 800, :y .<= 3410, :y .>= -2370), :color, polygons=polygons, min_molecules_per_cell=50,
    min_pixels_per_cell=7, polygon_alpha=0.5, ms=1.0, polygon_line_width=1.5, ticks=false)[1];

for ((xs, xe), (ys, ye)) in subset_coords
    plt = Plots.plot([xs, xs, xe, xe, xs], [ys, ye, ye, ys, ys], color="black", label="", lw=4.0, alpha=0.75)
end

@time Plots.savefig(plt, "$plot_dir/polygons.png");
display(plt)
Plots.closeall()
```
Sorry for this silly question because I have very limited coding skill on Julia.
Thanks for developing this tool
Zhang

**Comment by zhanglab2008** [comment]
I keep getting this error when I change the coordinates.
```bash
MethodError: no method matching getindex(::Makie.Figure, ::Int64)
Closest candidates are:
  getindex(::Makie.Figure, ::Any, ::Any) at /home/haojiawu/.julia/packages/Makie/06MOy/src/figures.jl:102
  getindex(::Makie.Figure, ::Any, ::Any, ::Any) at /home/haojiawu/.julia/packages/Makie/06MOy/src/figures.jl:102

Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/DataFramesMeta/z0mc6/src/macros.jl:420
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
```

**Comment by VPetukhov** [comment]
Hi Zhang, thanks for the kind words!
All examples in the paper are just illustrations of the approach, so we picked regions ourselves to show a few diverse regions. I'm yet to clean up the code, so apologies for the current state of it. This particular notebook wasn't updated since the first submission, while the code largely changed, hence the errors.

If you want just to plot the region, the correct version would be:

```julia
B.plot_dataset_colors(@where(df_spatial, :x .>= -3180, :x .<= 800, :y .<= 3410, :y .>= -2370), :color, polygons=polygons, min_molecules_per_cell=50, min_pixels_per_cell=7, markersize=1.0, poly_strokewidth=1.5)
```

Though the code below is harder to translate, so it won't show the black regions.

Is there anything particular you want to get from it? Maybe I might help with your end goal instead, as updating all notebooks could take a while.

**Comment by zhanglab2008** [comment]
Thanks so much, Viktor! I will give it a try with your updated code. I am still exploring the output files from baysor with the Jupiter notebook you shared. From the results I got so far, I am really impressed, and baysor improves the data quality a lot. I have another simple question if you don't mind. The output html file from baysor is very big. In my case, one of the html file has >1 Gb in size. I tried Safari, Chrome and Firefox but they all can't open it. I wonder what web browser you used to open the html file and extract the images from it? Thanks again in advance!

**Comment by VPetukhov** [comment]
> The output html file from baysor is very big. In my case, one of the html file has >1 Gb in size

Well, that's not supposed to be like that... Baysor [estimates the resolution](https://github.com/kharchenkolab/Baysor/blob/7333c767bdbb6d4ca6cc90b31e16dfe947e5625b/src/data_processing/diagnostic_plots.jl#L58) of the final plot based on the total number of molecules in your dataset, the minimal number of molecules per cell ([`-m`](https://github.com/kharchenkolab/Baysor#choice-of-parameters) CLI parameter) and the minimal number of pixels per cell ([`min-pixels-per-cell`](https://github.com/kharchenkolab/Baysor/blob/master/configs/example_config.toml#L47) in the config). Did you maybe set `-m` to a very small value? That's the most likely reason. Though if your data is genuinely huge (hundreds of millions of molecules) that can also be a problem. Or it can be a bug, which I missed.

**Comment by zhanglab2008** [comment]
Good catch! Thanks again Viktor! really nice work!

**Comment by VPetukhov** [comment]
Hi @zhanglab2008,
I updated the "MERFISH Hypothalamus" section in the [segmentation_panels.ipynb](https://github.com/kharchenkolab/BaysorAnalysis/blob/master/notebooks/segmentation/segmentation_panels.ipynb) (not the other ones, though). Now it should work with Baysor v0.5.0.

**Comment by zhanglab2008** [comment]
This is so awesome! Thanks Viktor. I will definitely try it out!
